# Generated by Django 5.1.7 on 2025-03-31 00:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PsychologistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rut', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Masculino'), ('FEMALE', 'Femenino'), ('OTHER', 'Otro'), ('PREFER_NOT_TO_SAY', 'Prefiero no decirlo')], max_length=20)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('professional_title', models.CharField(blank=True, max_length=100)),
                ('specialties', models.JSONField(blank=True, default=list)),
                ('health_register_number', models.CharField(blank=True, max_length=100)),
                ('university', models.CharField(blank=True, max_length=200)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)])),
                ('experience_description', models.TextField(blank=True)),
                ('target_populations', models.JSONField(blank=True, default=list)),
                ('intervention_areas', models.JSONField(blank=True, default=list)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('DOCUMENTS_SUBMITTED', 'Documentos Enviados'), ('VERIFICATION_IN_PROGRESS', 'En Verificación'), ('VERIFIED', 'Verificado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfessionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('DEGREE', 'Título Profesional'), ('LICENSE', 'Licencia Profesional'), ('CERTIFICATION', 'Certificación'), ('SPECIALTY', 'Especialidad'), ('OTHER', 'Otro')], max_length=50)),
                ('file', models.FileField(upload_to='psychologist_documents/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='profiles.psychologistprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_config', models.JSONField(default=dict)),
                ('psychologist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='profiles.psychologistprofile')),
            ],
        ),
    ]
