# Generated by Django 4.2.7 on 2025-04-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_clientprofile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="region",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="rut",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
