# Generated by Django 4.2.7 on 2025-04-01 22:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_clientprofile_city_clientprofile_region_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientprofile",
            name="city",
        ),
        migrations.RemoveField(
            model_name="clientprofile",
            name="region",
        ),
        migrations.RemoveField(
            model_name="clientprofile",
            name="rut",
        ),
    ]
