# Generated by Django 4.2.7 on 2025-04-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0008_psychologistprofile_bank_account_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminprofile",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="adminprofile",
            name="bank_account_owner",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="adminprofile",
            name="bank_account_owner_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="adminprofile",
            name="bank_account_owner_rut",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="adminprofile",
            name="bank_account_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CORRIENTE", "Cuenta Corriente"),
                    ("AHORRO", "Cuenta de Ahorro"),
                    ("VISTA", "Cuenta Vista"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="adminprofile",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="bank_account_owner",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="bank_account_owner_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="bank_account_owner_rut",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="bank_account_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CORRIENTE", "Cuenta Corriente"),
                    ("AHORRO", "Cuenta de Ahorro"),
                    ("VISTA", "Cuenta Vista"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
