# Generated by Django 4.2.7 on 2025-04-09 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0009_adminprofile_bank_account_number_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Schedule",
        ),
    ]
