# Generated by Django 4.2.7 on 2025-04-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0013_rename_phone_number_psychologistprofile_phone_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="psychologistprofile",
            options={
                "verbose_name": "Perfil de Psicólogo",
                "verbose_name_plural": "Perfiles de Psicólogos",
            },
        ),
        migrations.AddField(
            model_name="psychologistprofile",
            name="about_me",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="psychologistprofile",
            name="education",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="psychologistprofile",
            name="experience_years",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="psychologistprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MALE", "Masculino"),
                    ("FEMALE", "Femenino"),
                    ("OTHER", "Otro"),
                    ("PREFER_NOT_TO_SAY", "Prefiero no decir"),
                ],
                max_length=20,
            ),
        ),
    ]
