# Generated by Django 4.2.7 on 2025-04-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0014_alter_psychologistprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="psychologistprofile",
            options={},
        ),
        migrations.RemoveField(
            model_name="psychologistprofile",
            name="about_me",
        ),
        migrations.RemoveField(
            model_name="psychologistprofile",
            name="education",
        ),
        migrations.RemoveField(
            model_name="psychologistprofile",
            name="experience_years",
        ),
        migrations.RemoveField(
            model_name="psychologistprofile",
            name="suggested_price",
        ),
        migrations.AlterField(
            model_name="psychologistprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MALE", "Masculino"),
                    ("FEMALE", "Femenino"),
                    ("OTHER", "Otro"),
                    ("PREFER_NOT_TO_SAY", "Prefiero no decirlo"),
                ],
                max_length=20,
            ),
        ),
    ]
