# Generated by Django 4.2.7 on 2025-04-11 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profiles", "0015_alter_psychologistprofile_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_price", models.IntegerField(default=5000)),
                ("max_price", models.IntegerField(default=50000)),
                ("platform_fee_percentage", models.IntegerField(default=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Price Configuration",
                "verbose_name_plural": "Price Configurations",
            },
        ),
        migrations.CreateModel(
            name="SuggestedPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "psychologist",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_price",
                        to="profiles.psychologistprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suggested Price",
                "verbose_name_plural": "Suggested Prices",
            },
        ),
        migrations.CreateModel(
            name="PsychologistPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField()),
                ("is_approved", models.BooleanField(default=False)),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "psychologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="profiles.psychologistprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Psychologist Price",
                "verbose_name_plural": "Psychologist Prices",
            },
        ),
        migrations.CreateModel(
            name="PriceChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_price", models.IntegerField()),
                ("requested_price", models.IntegerField()),
                ("justification", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "psychologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_change_requests",
                        to="profiles.psychologistprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price Change Request",
                "verbose_name_plural": "Price Change Requests",
            },
        ),
    ]
