# Generated by Django 4.2.7 on 2025-04-11 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0001_initial"),
    ]

    operations = []
