# Generated by Django 4.2.7 on 2025-04-14 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0015_alter_psychologistprofile_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Fecha de la cita")),
                ("start_time", models.TimeField(help_text="Hora de inicio de la cita")),
                ("end_time", models.TimeField(help_text="Hora de fin de la cita")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_PAYMENT", "Pendiente de Pago"),
                            ("PAYMENT_UPLOADED", "Comprobante Subido"),
                            ("PAYMENT_VERIFIED", "Pago Verificado"),
                            ("CONFIRMED", "Confirmada"),
                            ("COMPLETED", "Completada"),
                            ("CANCELLED", "Cancelada"),
                            ("NO_SHOW", "No Asistió"),
                        ],
                        default="PENDING_PAYMENT",
                        help_text="Estado actual de la cita",
                        max_length=20,
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monto a pagar por la cita",
                        max_digits=10,
                    ),
                ),
                (
                    "payment_proof",
                    models.FileField(
                        blank=True,
                        help_text="Comprobante de pago subido por el cliente",
                        null=True,
                        upload_to="payment_proofs/",
                    ),
                ),
                (
                    "client_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notas adicionales proporcionadas por el cliente",
                        null=True,
                    ),
                ),
                (
                    "psychologist_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notas privadas del psicólogo sobre la cita",
                        null=True,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notas administrativas sobre la cita",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Cliente que solicita la cita",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="profiles.clientprofile",
                    ),
                ),
                (
                    "payment_verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Administrador que verificó el pago",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "psychologist",
                    models.ForeignKey(
                        help_text="Psicólogo que atenderá la cita",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="profiles.psychologistprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cita",
                "verbose_name_plural": "Citas",
                "ordering": ["-date", "start_time"],
                "unique_together": {("psychologist", "date", "start_time")},
            },
        ),
        migrations.CreateModel(
            name="PaymentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="ID de la transacción bancaria",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora del pago según el cliente",
                        null=True,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        help_text="Método de pago utilizado",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        help_text="Cita asociada al pago",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_detail",
                        to="appointments.appointment",
                    ),
                ),
            ],
        ),
    ]
