# Generated by Django 4.2.7 on 2025-04-30 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0004_appointment_is_first_appointment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
