# Generated by Django 4.2.7 on 2025-04-09 20:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profiles", "0011_psychologistprofile_suggested_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_price",
                    models.PositiveIntegerField(
                        default=5000,
                        help_text="Precio mínimo permitido en CLP",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_price",
                    models.PositiveIntegerField(
                        default=15000,
                        help_text="Precio máximo permitido en CLP",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "platform_fee_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Porcentaje de comisión de la plataforma",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración de Precios",
                "verbose_name_plural": "Configuraciones de Precios",
            },
        ),
        migrations.CreateModel(
            name="PromotionalDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la promoción", max_length=100
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Código promocional", max_length=20, unique=True
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Porcentaje de descuento",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(help_text="Fecha de inicio de la promoción"),
                ),
                (
                    "end_date",
                    models.DateTimeField(help_text="Fecha de fin de la promoción"),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        default=100, help_text="Número máximo de usos permitidos"
                    ),
                ),
                (
                    "current_uses",
                    models.PositiveIntegerField(
                        default=0, help_text="Número actual de usos"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Descuento Promocional",
                "verbose_name_plural": "Descuentos Promocionales",
            },
        ),
        migrations.CreateModel(
            name="PsychologistPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        help_text="Precio asignado por el administrador en CLP",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el precio ha sido aprobado por el administrador",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notas del administrador sobre la decisión de precio",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "psychologist",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_price",
                        to="profiles.psychologistprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Precio de Psicólogo",
                "verbose_name_plural": "Precios de Psicólogos",
            },
        ),
        migrations.CreateModel(
            name="PriceChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_price",
                    models.PositiveIntegerField(
                        help_text="Precio actual en CLP",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "requested_price",
                    models.PositiveIntegerField(
                        help_text="Precio solicitado en CLP (máximo 15000 CLP)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(15000),
                        ],
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        help_text="Justificación para el cambio de precio"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("approved", "Aprobado"),
                            ("rejected", "Rechazado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notas del administrador sobre la decisión",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "psychologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_change_requests",
                        to="profiles.psychologistprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Cambio de Precio",
                "verbose_name_plural": "Solicitudes de Cambio de Precio",
                "ordering": ["-created_at"],
            },
        ),
    ]
