# Generated by Django 4.2.7 on 2025-04-11 19:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0002_auto_20250411_1506"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="suggestedprice",
            table="pricing_suggestedprice",
        ),
    ]
