# Generated by Django 4.2.7 on 2025-04-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_professionaldocument_rejection_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MALE", "Masculino"),
                    ("FEMALE", "Femenino"),
                    ("OTHER", "Otro"),
                    ("PREFER_NOT_TO_SAY", "Prefiero no decirlo"),
                ],
                max_length=20,
            ),
        ),
    ]
