# Generated by Django 4.2.7 on 2025-04-09 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0010_remove_schedule_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="psychologistprofile",
            name="suggested_price",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Precio sugerido por el psicólogo (máximo 15000 CLP)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(15000),
                ],
            ),
        ),
    ]
