# Generated by Django 4.2.7 on 2025-04-10 01:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0011_psychologistprofile_suggested_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="psychologistprofile",
            old_name="phone",
            new_name="phone_number",
        ),
        migrations.AlterField(
            model_name="psychologistprofile",
            name="graduation_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="psychologistprofile",
            name="health_register_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="psychologistprofile",
            name="suggested_price",
            field=models.IntegerField(
                blank=True,
                help_text="Precio sugerido por el psicólogo para sus consultas (en CLP)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(15000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="psychologistprofile",
            name="university",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
