# Generated by Django 4.2.7 on 2025-04-10 01:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0012_rename_phone_psychologistprofile_phone_number_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="psychologistprofile",
            old_name="phone_number",
            new_name="phone",
        ),
        migrations.AlterField(
            model_name="psychologistprofile",
            name="graduation_year",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1950),
                    django.core.validators.MaxValueValidator(2100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="psychologistprofile",
            name="health_register_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="psychologistprofile",
            name="suggested_price",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Precio sugerido por el psicólogo (máximo 15000 CLP)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(15000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="psychologistprofile",
            name="university",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
