# Generated by Django 4.2.7 on 2025-04-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0015_alter_psychologistprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientprofile",
            name="bank_account_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CORRIENTE", "Cuenta Corriente"),
                    ("AHORRO", "Cuenta de Ahorro"),
                    ("VISTA", "Cuenta Vista"),
                    ("RUT", "Cuenta RUT"),
                ],
                max_length=20,
            ),
        ),
    ]
