# Generated by Django 4.2.7 on 2025-04-24 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0016_alter_clientprofile_bank_account_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="psychologistprofile",
            name="experience_description",
        ),
        migrations.CreateModel(
            name="ProfessionalExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "experience_type",
                    models.CharField(
                        choices=[
                            ("PRACTICUM", "Pasantía"),
                            ("ASSISTANTSHIP", "Ayudantía"),
                            ("WORK", "Trabajo"),
                            ("VOLUNTEERING", "Voluntariado"),
                            ("OTHER", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("institution", models.CharField(max_length=200)),
                ("role", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                (
                    "psychologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="profiles.psychologistprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
    ]
