# Generated by Django 4.2.7 on 2025-05-02 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0017_remove_psychologistprofile_experience_description_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE profiles_psychologistprofile ALTER COLUMN experience_description DROP NOT NULL;",
            "ALTER TABLE profiles_psychologistprofile ALTER COLUMN experience_description SET NOT NULL;"
        ),
    ]
