# Generated by Django 4.2.7 on 2025-04-08 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0009_adminprofile_bank_account_number_and_more"),
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointmentreminder",
            name="appointment",
        ),
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["date", "start_time"]},
        ),
        migrations.RemoveConstraint(
            model_name="appointment",
            name="unique_appointment_time",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="psychologist_notes",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="psychologist_profile",
        ),
        migrations.AddField(
            model_name="appointment",
            name="psychologist",
            field=models.ForeignKey(
                db_column="psychologist_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="psychologist_appointments",
                to="profiles.psychologistprofile",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="client_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("CONFIRMED", "Confirmada"),
                    ("CANCELLED", "Cancelada"),
                    ("COMPLETED", "Completada"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                fields=("psychologist", "date", "start_time"),
                name="unique_appointment_slot",
            ),
        ),
        migrations.DeleteModel(
            name="AppointmentReminder",
        ),
    ]
