# Generated by Django 4.2.7 on 2025-04-14 20:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        # Comment out or remove the DeleteModel operation
        # migrations.DeleteModel(
        #     name='PaymentDetail',
        # ),
    ]
