# Generated by Django 4.2.7 on 2025-04-08 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0009_adminprofile_bank_account_number_and_more"),
        ("appointments", "0002_remove_appointmentreminder_appointment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="psychologist",
            field=models.ForeignKey(
                db_column="psychologist_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="psychologist_appointments",
                to="profiles.psychologistprofile",
            ),
            preserve_default=False,
        ),
    ]
