# Generated by Django 4.2.7 on 2025-04-14 23:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0002_delete_paymentdetail"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PaymentDetail",
        ),
    ]
