# Generated by Django 4.2.7 on 2025-04-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0003_delete_paymentdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="is_first_appointment",
            field=models.BooleanField(
                default=False,
                help_text="Indica si esta cita es la primera entre el cliente y el psicólogo",
            ),
        ),
    ]
