# Generated by Django 4.2.7 on 2025-04-09 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0010_remove_schedule_model"),
        ("appointments", "0004_alter_appointment_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                ("created_by", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["-date", "-start_time"]},
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="client_notes",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="payment_amount",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="payment_date",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="payment_id",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="psychologist_notes",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="profiles.clientprofile",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="psychologist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="profiles.psychologistprofile",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("confirmed", "Confirmada"),
                    ("cancelled", "Cancelada"),
                    ("completed", "Completada"),
                    ("rescheduled", "Reprogramada"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                fields=("psychologist", "date", "start_time"),
                name="unique_psychologist_appointment",
            ),
        ),
        migrations.AddField(
            model_name="appointmentnote",
            name="appointment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment_notes",
                to="appointments.appointment",
            ),
        ),
    ]
