# Generated by Django 4.2.7 on 2025-04-09 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0011_psychologistprofile_suggested_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("appointments", "0005_appointmentnote_alter_appointment_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointmentnote",
            name="appointment",
        ),
        migrations.AlterModelOptions(
            name="appointment",
            options={
                "ordering": ["-date", "-start_time"],
                "verbose_name": "Cita",
                "verbose_name_plural": "Citas",
            },
        ),
        migrations.RemoveConstraint(
            model_name="appointment",
            name="unique_psychologist_appointment",
        ),
        migrations.AddField(
            model_name="appointment",
            name="client_notes",
            field=models.TextField(
                blank=True, help_text="Notas privadas del cliente", null=True
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="payment_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="payment_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="psychologist_notes",
            field=models.TextField(
                blank=True, help_text="Notas privadas del psicólogo", null=True
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Notas del cliente para el psicólogo", null=True
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="psychologist",
            field=models.ForeignKey(
                db_column="psychologist_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="psychologist_appointments",
                to="profiles.psychologistprofile",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("CONFIRMED", "Confirmada"),
                    ("CANCELLED", "Cancelada"),
                    ("COMPLETED", "Completada"),
                    ("PAYMENT_PENDING", "Pago Pendiente"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="AppointmentNote",
        ),
    ]
