# Generated by Django 4.2.7 on 2025-04-09 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profiles", "0010_remove_schedule_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("MONDAY", "Lunes"),
                            ("TUESDAY", "Martes"),
                            ("WEDNESDAY", "Miércoles"),
                            ("THURSDAY", "Jueves"),
                            ("FRIDAY", "Viernes"),
                            ("SATURDAY", "Sábado"),
                            ("SUNDAY", "Domingo"),
                        ],
                        help_text="Día de la semana",
                        max_length=10,
                    ),
                ),
                ("start_time", models.TimeField(help_text="Hora de inicio")),
                ("end_time", models.TimeField(help_text="Hora de fin")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "psychologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="profiles.psychologistprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horario",
                "verbose_name_plural": "Horarios",
                "ordering": ["day_of_week", "start_time"],
                "unique_together": {
                    ("psychologist", "day_of_week", "start_time", "end_time")
                },
            },
        ),
    ]
