# Generated by Django 4.2.7 on 2025-04-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedules", "0001_create_schedule_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="user_id",
            field=models.IntegerField(
                blank=True,
                help_text="ID del usuario autenticado que creó o actualizó este horario",
                null=True,
            ),
        ),
    ]
